### ISSUE TITLE
Экран бронирования билетов

### ISSUE THREAD

**Issue by dvaschenko** [alkhachaturian/homework-5#3]
Поля в фильтре разбежались. Просто замечание, понимаю, что Вы скорее всего пытались добиться соответствия условию задачи, про 100 процентов ширины. Думаю, уберём это из условия.
Таблица рейсов расширяется родителем - height="100%" не нужен. Опечатка в имени колонки - tactions/actions
Используется блокирующий вызов фоновой задачи - return handler.getResult(); Это, конечно, Ваше решение как разработчика, как использовать указанные задачи. Можно сделать неблокирующим:
````
        BackgroundTask<Integer, List<Flight>> task = new BackgroundTask<>(30) {

            @Override
            public List<Flight> run(TaskLifeCycle<Integer> taskLifeCycle) throws Exception {
                List<Flight> flights = ticketService.searchFlights(fromPort, toPort,
                        departureDate == null
                                ? null
                                : departureDate.toLocalDate());

                return flights;
            }

            @Override
            public void done(List<Flight> result) {
                if (!result.isEmpty()) {
                    flightsDc.setItems(result);  //здесь элементы будут проставлены в CollectionContainer
                } else {
                    flightsDc.getMutableItems().clear();
                }
                progressBar.setVisible(false);
            }
        };

        BackgroundTaskHandler<List<Flight>> taskHandler = backgroundWorker.handle(task);
        taskHandler.execute();
        progressBar.setVisible(true);
    }
````

ProgressBar не работает как ожидалось, проверьте, где вы его включаете и выключаете, попробуйте переделать на неблокирующий вызов, как в сниппете выше. В остальном всё хорошо, отличная работа.)

**Comment by alkhachaturian** [comment]
переделала для неблокирующего вызова
